### ISSUE TITLE
Watchnixtoons Chapters and Autoplay 

### ISSUE THREAD

**Issue by rogermae** [doko-desuka/doko.repository#10]
I'm on a firestick 4k with kodi 18 2. I used to be able to binge watch dubbed shows but now have to select chapter 1 or 2 before the episode starts. What is this chapter thing and how can I bypass it.

**Comment by doko-desuka** [comment]
@rogermae that only comes up when, on the source website, the episode page has two different video players instead of the usual single video player.  

On some series like SpongeBob, Archer etc. each of the two video players on the web page play a different "chapter" of the episode (they're different parts). I think it was @bjgood that first warned me about this.  
On other series it doesn't mean anything, there might be two video players but they just point to the same episode.  

So I now changed it to be a context menu item. If you long-press or right-click on a playable item, the Kodi context menu will show up and there'll be a "Play Chapters" option at the top.  
If you select this option it'll play the episode but try to see if there are any chapters, and show you that selection dialog if they're there. If they're not there then it just plays as normal.
So now you need to deliberately use that context menu to play multi-chapter episodes.

**Comment by rogermae** [comment]
Got it, thanks

Kind Regards,
Roz

________________________________
